services:
  - type: web
    name: backend-alvis
    env: php
    buildCommand: |
      composer install
      php artisan key:generate --force
      php artisan migrate --force || true
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    plan: free
